services:
  nuxeo:
    image: docker-internal.packages.nuxeo.com/nuxeo/nuxeo-mcp-demo:2025
    environment:
      - NUXEO_DEV_MODE=true
    ports:
      - "8080:8080"
    networks:
      - mcp-network

  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NUXEO_URL=http://nuxeo:8080/nuxeo
      - NUXEO_USERNAME=Administrator
      - NUXEO_PASSWORD=Administrator
    ports:
      - "8081:8181"
    depends_on:
      - nuxeo
    networks:
      - mcp-network

  agent0:
    image: agent0ai/agent-zero
    environment:
      - NUXEO_DEV_MODE=true
    ports:
      - "50001:80"
    depends_on:
      - mcp
    networks:
      - mcp-network


networks:
  mcp-network:
    driver: bridge
