version: '3'

services:
  nuxeo:
    image: docker-private.packages.nuxeo.com/nuxeo/nuxeo:2025
    environment:
      - NUXEO_DEV_MODE=true
    ports:
      - "8080:8080"
    networks:
      - mcp-network

  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NUXEO_URL=http://nuxeo:8080/nuxeo
      - NUXEO_USERNAME=Administrator
      - NUXEO_PASSWORD=Administrator
      - MCP_MODE=sse
      - MCP_PORT=8181
      - MCP_HOST=0.0.0.0
    ports:
      - "8081:8181"
    depends_on:
      - nuxeo
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
