name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Login to Nuxeo Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker-private.packages.nuxeo.com
        username: ${{ secrets.NUXEO_DOCKER_USERNAME }}
        password: ${{ secrets.NUXEO_DOCKER_PASSWORD }}
        
    - name: Pull Nuxeo Docker Image
      run: |
        docker pull docker-private.packages.nuxeo.com/nuxeo/nuxeo:2025
        
    - name: Run integration tests
      env:
        NUXEO_DOCKER_IMAGE: docker-private.packages.nuxeo.com/nuxeo/nuxeo:2025
      run: |
        python -m pytest tests/ -v --integration
